#!/usr/bin/env python3
"""
Monta o texto do comentário de fechamento da issue do portão de entrada,
juntando os resultados de aplicar_decisoes.py, atualizar_marcos.py e
revisar_ignorados.py (arquivos JSON deixados em /tmp pelo workflow
.github/workflows/portao_atualizar.yml).

Imprime o comentário em stdout. Sai com código 0 se a issue deve ser
fechada, 1 se deve ficar aberta (decisão malformada ou processo não
encontrado na fila — precisa de atenção manual).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def carregar(caminho: str):
    p = Path(caminho)
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def main() -> int:
    aplicar = carregar("/tmp/resultado_aplicar.json")
    marcos = carregar("/tmp/resultado_marcos.json")
    ignorados = carregar("/tmp/resultado_ignorados.json")

    partes: list[str] = []
    deve_fechar = True

    if aplicar is not None:
        if aplicar.get("nao_encontrados_na_fila"):
            deve_fechar = False
            numeros = ", ".join(str(n) for n in aplicar["nao_encontrados_na_fila"])
            partes.append(
                f"⚠️ Alguns processos da issue não foram encontrados na fila do portão ({numeros}) — "
                "provavelmente a issue foi criada a partir de uma versão desatualizada do painel. "
                "Dê um F5 no painel, decida de novo no portão e clique em \"Entrar no painel\" — "
                "essa issue fica aberta, pode fechar manualmente depois de conferir."
            )
        else:
            if aplicar.get("acompanhados"):
                partes.append("✅ Acompanhando: " + ", ".join(aplicar["acompanhados"]))
            if aplicar.get("ignorados"):
                partes.append("🚫 Ignorados: " + ", ".join(aplicar["ignorados"]))
            if not aplicar.get("acompanhados") and not aplicar.get("ignorados"):
                partes.append("Nenhuma decisão nova aplicada.")

    if marcos is not None:
        partes.append(
            f"🔄 Atualização geral: {marcos.get('atualizados', 0)} processo(s) atualizado(s) "
            f"de {marcos.get('processos_verificados', 0)} verificados."
        )
        if marcos.get("avisos"):
            partes.append(f"⚠️ {len(marcos['avisos'])} aviso(s) gerado(s) — conferir manualmente quando puder.")

    if ignorados is not None and ignorados.get("voltaram_ao_portao"):
        partes.append(
            f"↩️ {ignorados['voltaram_ao_portao']} processo(s) ignorado(s) voltaram a se "
            "movimentar e retornaram ao portão."
        )

    if not partes:
        partes.append("Nada pra reportar nesta rodada.")

    partes.append("---\n_Generated by [Claude Code](https://claude.ai/code)_")
    print("\n\n".join(partes))
    return 0 if deve_fechar else 1


if __name__ == "__main__":
    sys.exit(main())
